# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Archive"
  lane :archive do |options|

    workspace = options[:workspace]
    fail ArgumentError, "missing workspace" unless workspace

    match(type: "appstore")
    gym(export_method: "app-store", workspace: workspace, include_bitcode: false)
  end

end
