# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

files_with_version_number = {
    './.version' => ['{x}'],
    './RevenueCat/Plugins/iOS/PurchasesUnityHelper.m' => ['return @"{x}"'],
    './RevenueCat/Plugins/Android/PurchasesWrapper.java' => ['PLUGIN_VERSION = "{x}"'],
    './RevenueCat/package.json' => ['"version": "{x}"']
}
ANDROID_PHC_DEPENDENCY_PATTERN = 'com.revenuecat.purchases:purchases-hybrid-common:[{x}]'
files_to_update_phc_version = {
    'RevenueCat/Plugins/Editor/RevenueCatDependencies.xml' => [
        ANDROID_PHC_DEPENDENCY_PATTERN,
        'name="PurchasesHybridCommon" version="{x}"'
    ],
    'Subtester/Assets/Plugins/Android/mainTemplate.gradle' => [ANDROID_PHC_DEPENDENCY_PATTERN],
    'Subtester/ProjectSettings/AndroidResolverDependencies.xml' => [ANDROID_PHC_DEPENDENCY_PATTERN],
}
repo_name = 'purchases-unity'
changelog_latest_path = './CHANGELOG.latest.md'
changelog_path = './CHANGELOG.md'
versions_path = './VERSIONS.md'

before_all do
  setup_circle_ci
  update_fastlane
end

desc "Bump version, edit changelog, and create pull request"
lane :bump do |options|
  bump_version_update_changelog_create_pr(
    current_version: current_version_number,
    changelog_latest_path: changelog_latest_path,
    changelog_path: changelog_path,
    files_to_update: files_with_version_number,
    repo_name: repo_name,
    github_rate_limit: options[:github_rate_limit],
    editor: options[:editor],
    next_version: options[:next_version],
    automatic_release: options[:automatic_release],
    hybrid_common_version: get_phc_version,
    versions_file_path: versions_path
  )
  update_versions_file
end

desc "Automatically bumps version, edit changelog, and create pull request"
lane :automatic_bump do |options|
  next_version, type_of_bump = determine_next_version_using_labels(
    repo_name: repo_name,
    github_rate_limit: options[:github_rate_limit],
    current_version: current_version_number
  )
  options[:next_version] = next_version
  options[:automatic_release] = true
  if type_of_bump == :skip
    UI.message('Skipping automatic bump since the next version doesn\'t include public facing changes')
    next
  end
  if type_of_bump == :major
    UI.message('Skipping automatic bump since the next version is a major release')
    next
  end
  bump(options)
end

desc "Make github release"
lane :github_release do |options|
  create_github_release(
    version: current_version_number,
    repo_name: repo_name,
    github_api_token: ENV["GITHUB_TOKEN"],
    changelog_latest_path: changelog_latest_path,
    upload_assets: ['Purchases.unitypackage']
  )
end

desc "Update hybrid common pod and gradle and pushes changes to a new branch if open_pr option is true"
lane :update_hybrid_common do |options|
  if options[:dry_run]
    dry_run = true
  end
  if options[:version]
    new_version_number = options[:version]
  else
    UI.user_error!("Missing `version` argument")
  end

  current_phc_version = get_phc_version

  UI.message("ℹ️  Current Purchases Hybrid Common version: #{current_phc_version}")
  UI.message("ℹ️  Setting Purchases Hybrid Common version: #{new_version_number}")

  if dry_run
    UI.message("ℹ️  Nothing more to do, dry_run: true")
    next
  end

  bump_phc_version(
    repo_name: repo_name,
    files_to_update: files_to_update_phc_version,
    current_version: current_phc_version,
    next_version: new_version_number,
    open_pr: options[:open_pr] || false,
    automatic_release: options[:automatic_release] || false
  )
end

desc "Tag current branch with current version number"
lane :tag_current_branch do |options|
  version_number = current_version_number
  check_no_git_tag_exists(version_number)

  add_git_tag(tag: version_number)
  push_git_tags(tag: version_number)
end

###############################################################################
# Helper functions 🤜🤛                                                      #
###############################################################################

def update_versions_file
  versions_file_path = './VERSIONS.md'
  update_hybrids_versions_file(
    versions_file_path: versions_file_path,
    new_sdk_version: current_version_number,
    hybrid_common_version: get_phc_version
  )
  append_previous_version_compatibility_to_versions_file(versions_file_path)
  commit_current_changes(commit_message: 'Update VERSIONS.md')
  push_to_git_remote(set_upstream: true)
end

# The update_hybrids_versions_file action updates the version file with the columns:
# | Version | iOS version | Android version | Common version |
# This function appends a new column to the above columns, so the result looks like this:
# | Version | iOS version | Android version | Common version | Unity IAP compatibility |
# This picks the `Unity IAP compatibility`` value of the last version in the VERSIONS.md file
# before the last row was added. If this changes, it needs to be updated manually.
def append_previous_version_compatibility_to_versions_file(versions_file_path)
  Dir.chdir(get_root_folder) do
    File.open(versions_file_path, 'r+') do |file|
      lines = file.each_line.to_a
      # This gets the row of the last version released, and gets the value of the last column. Example:
      # | Version | iOS version | Android version | Common version | Unity IAP compatibility |
      # |---------|-------------|-----------------|----------------|-------------------------|
      # | 4.1.0   | 4.10.1      | 5.4.1           | 4.1.2          | Unity IAP 3.3.0+        |
      # | 4.0.0   | 4.9.0       | 5.3.0           | 3.3.0          | Unity IAP 3.3.0+        |
      previous_to_last_version_compatibility = lines[3].split('|')[-2].strip
      lines[2] = lines[2].strip + " #{previous_to_last_version_compatibility} |\n"
      file.rewind
      file.write(lines.join)
    end
  end
end

def get_phc_version
  file_contents = File.read('../RevenueCat/Plugins/Editor/RevenueCatDependencies.xml')
  # This will parse the PHC version for iOS and android from within the RevenueCat/Plugins/Editor/RevenueCatDependencies.xml file
  # iOS appears in the form: <iosPod name="PurchasesHybridCommon" version="4.1.2" minTargetSdk="11.0"/>
  ios_phc_version = file_contents.split("<iosPod name=\"PurchasesHybridCommon\" version=")[1].split()[0].tr('"', '')
   # Android appears in the form: <androidPackage spec="com.revenuecat.purchases:purchases-hybrid-common:[4.1.2]" />
  android_phc_version = file_contents.split("<androidPackage spec=\"com.revenuecat.purchases:purchases-hybrid-common:[")[1].split(']')[0]

  UI.error("PHC version does not match between iOS and android in RevenueCat/Plugins/Editor/RevenueCatDependencies.xml. Please check those values") if ios_phc_version != android_phc_version

  ios_phc_version
end

def get_root_folder
  return File.expand_path('../../', __FILE__)
end

def current_version_number
  File.read("../.version")
end

def check_no_git_tag_exists(version_number)
  if git_tag_exists(tag: version_number, remote: true, remote_name: 'origin')
    raise "git tag with version #{version_number} already exists!"
  end
end